create table if not exists public."PushTokens" (
  id bigint generated by default as identity primary key,
  user_id text not null references public."User"(id) on delete cascade,
  token text not null unique,
  platform text null,
  is_active boolean not null default true,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now()
);

create index if not exists idx_push_tokens_user_id
  on public."PushTokens"(user_id);

create index if not exists idx_push_tokens_user_active
  on public."PushTokens"(user_id, is_active);

create or replace function public.set_push_tokens_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_push_tokens_updated_at on public."PushTokens";
create trigger trg_push_tokens_updated_at
before update on public."PushTokens"
for each row execute function public.set_push_tokens_updated_at();
