/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/driver-setup`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/role`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/driver/AvailableRiders`; params?: Router.UnknownInputParams; } | { pathname: `/driver/DriverWaitingRoom`; params?: Router.UnknownInputParams; } | { pathname: `/driver/OfferRide`; params?: Router.UnknownInputParams; } | { pathname: `/driver/RideDetail`; params?: Router.UnknownInputParams; } | { pathname: `/driver/ScheduledRidesDriver`; params?: Router.UnknownInputParams; } | { pathname: `/rider/AvailableDrivers`; params?: Router.UnknownInputParams; } | { pathname: `/rider/RequestRide`; params?: Router.UnknownInputParams; } | { pathname: `/rider/RideDetailRider`; params?: Router.UnknownInputParams; } | { pathname: `/rider/RiderWaitingRoom`; params?: Router.UnknownInputParams; } | { pathname: `/rider/ScheduledRidesRider`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/driver-setup`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/role`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/driver/AvailableRiders`; params?: Router.UnknownOutputParams; } | { pathname: `/driver/DriverWaitingRoom`; params?: Router.UnknownOutputParams; } | { pathname: `/driver/OfferRide`; params?: Router.UnknownOutputParams; } | { pathname: `/driver/RideDetail`; params?: Router.UnknownOutputParams; } | { pathname: `/driver/ScheduledRidesDriver`; params?: Router.UnknownOutputParams; } | { pathname: `/rider/AvailableDrivers`; params?: Router.UnknownOutputParams; } | { pathname: `/rider/RequestRide`; params?: Router.UnknownOutputParams; } | { pathname: `/rider/RideDetailRider`; params?: Router.UnknownOutputParams; } | { pathname: `/rider/RiderWaitingRoom`; params?: Router.UnknownOutputParams; } | { pathname: `/rider/ScheduledRidesRider`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/driver-setup${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/role${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/driver/AvailableRiders${`?${string}` | `#${string}` | ''}` | `/driver/DriverWaitingRoom${`?${string}` | `#${string}` | ''}` | `/driver/OfferRide${`?${string}` | `#${string}` | ''}` | `/driver/RideDetail${`?${string}` | `#${string}` | ''}` | `/driver/ScheduledRidesDriver${`?${string}` | `#${string}` | ''}` | `/rider/AvailableDrivers${`?${string}` | `#${string}` | ''}` | `/rider/RequestRide${`?${string}` | `#${string}` | ''}` | `/rider/RideDetailRider${`?${string}` | `#${string}` | ''}` | `/rider/RiderWaitingRoom${`?${string}` | `#${string}` | ''}` | `/rider/ScheduledRidesRider${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/driver-setup`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/role`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/driver/AvailableRiders`; params?: Router.UnknownInputParams; } | { pathname: `/driver/DriverWaitingRoom`; params?: Router.UnknownInputParams; } | { pathname: `/driver/OfferRide`; params?: Router.UnknownInputParams; } | { pathname: `/driver/RideDetail`; params?: Router.UnknownInputParams; } | { pathname: `/driver/ScheduledRidesDriver`; params?: Router.UnknownInputParams; } | { pathname: `/rider/AvailableDrivers`; params?: Router.UnknownInputParams; } | { pathname: `/rider/RequestRide`; params?: Router.UnknownInputParams; } | { pathname: `/rider/RideDetailRider`; params?: Router.UnknownInputParams; } | { pathname: `/rider/RiderWaitingRoom`; params?: Router.UnknownInputParams; } | { pathname: `/rider/ScheduledRidesRider`; params?: Router.UnknownInputParams; };
    }
  }
}
