import { StyleSheet, Platform } from 'react-native';
import { B } from './SetupIcons';

export const s = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: B.bg },
  flex1: { flex: 1 },
  scrollContent: { paddingHorizontal: 24, paddingTop: 40, paddingBottom: 32 },

  // Header
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 8,
  },
  backBtn: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  backText: { fontSize: 13, fontWeight: '700', color: B.muted },
  skipSetup: { fontSize: 13, fontWeight: '700', color: B.muted },

  // Progress
  progressContainer: { paddingHorizontal: 24, marginTop: 12 },
  progressLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  progressLabel: { fontSize: 10, fontWeight: '800', color: B.slate300, letterSpacing: 2, textTransform: 'uppercase' },
  progressPercent: { fontSize: 11, fontWeight: '700', color: B.blue },
  progressTrack: {
    height: 4,
    backgroundColor: B.slate100,
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: B.blue,
    borderRadius: 2,
  },

  // Content Elements
  stepHeader: { marginBottom: 16, paddingTop: 16 },
  eyebrow: {
    fontSize: 11,
    fontWeight: '700',
    color: B.blue,
    textTransform: 'uppercase',
    letterSpacing: 2,
    marginBottom: 8,
  },
  question: {
    fontSize: 24,
    fontWeight: '800',
    color: B.text,
    lineHeight: 32,
  },
  hint: {
    fontSize: 15,
    color: B.slate400,
    marginTop: 12,
    fontWeight: '500',
    lineHeight: 22,
  },

  // Text input
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: B.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: B.slate200,
    paddingHorizontal: 20,
    paddingVertical: Platform.OS === 'ios' ? 18 : 14,
  },
  inputIcon: { marginRight: 12 },
  textInput: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: B.text,
    outlineStyle: 'none',
  },
  textInputDisabled: { color: B.muted, fontStyle: 'italic' },

  // Checkbox row
  checkRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingLeft: 4 },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: B.slate300,
    backgroundColor: B.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: { backgroundColor: B.blue, borderColor: B.blue },
  checkLabel: { fontSize: 13, fontWeight: '700', color: B.slate400 },
  checkLabelUpper: {
    fontSize: 11,
    fontWeight: '800',
    color: B.slate500,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },

  // Schedule card
  card: {
    backgroundColor: B.white,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: B.slate200,
    padding: 24,
    gap: 24,
  },
  row: { flexDirection: 'row', gap: 12 },
  halfField: { flex: 1 },
  fieldLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: B.slate400,
    textTransform: 'uppercase',
    letterSpacing: 2,
    marginLeft: 4,
  },
  inlineLabelRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  fieldInput: {
    backgroundColor: B.slate50,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: B.slate100,
    paddingVertical: 12,
    paddingHorizontal: 16,
    justifyContent: 'center',
    height: 48,
    outlineStyle: 'none',
    marginTop: 8,
  },
  smallInput: {
    backgroundColor: B.slate50,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: B.slate100,
    paddingVertical: 8,
    paddingHorizontal: 12,
    justifyContent: 'center',
    height: 40,
    outlineStyle: 'none',
    marginTop: 8,
    fontSize: 13,
    fontWeight: '600',
    color: B.text,
  },
  fieldInputText: { fontSize: 14, fontWeight: '700', color: B.text, outlineStyle: 'none' },

  // Days
  daysRow: { flexDirection: 'row', gap: 4 },
  dayBtn: {
    flex: 1,
    height: 40,
    borderRadius: 12,
    backgroundColor: B.slate50,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: B.slate100,
  },
  dayBtnSelected: { backgroundColor: B.blue, borderColor: B.blue },
  dayBtnText: { fontSize: 13, fontWeight: '700', color: B.slate400, textTransform: 'uppercase' },
  dayBtnTextSelected: { color: B.white },
  dimmed: { opacity: 0.4 },

  addBtn: {
    backgroundColor: B.slate100,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 8,
  },
  addBtnDisabled: { opacity: 0.5 },
  addBtnText: { fontSize: 14, fontWeight: '700', color: B.text },

  // Active blocks
  sectionDivider: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  sectionLabel: { fontSize: 11, fontWeight: '800', color: B.slate400, textTransform: 'uppercase', letterSpacing: 2 },
  dividerLine: { flex: 1, height: 1, backgroundColor: B.slate200 },
  emptyText: { fontSize: 14, color: B.slate400, fontStyle: 'italic', textAlign: 'center', paddingVertical: 12 },
  blockItem: {
    backgroundColor: B.white,
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: B.slate200,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  blockDays: {
    fontSize: 12,
    fontWeight: '800',
    color: B.blue,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  blockTime: { fontSize: 15, fontWeight: '800', color: B.text, marginBottom: 20 },
  blockRoute: { flexDirection: 'row', paddingLeft: 28 },
  routeLine: {
    position: 'absolute',
    left: 1,
    top: 6,
    bottom: 6,
    width: 1,
    borderLeftWidth: 1,
    borderStyle: 'dashed',
    borderColor: B.slate200,
  },
  routeStops: { gap: 16 },
  routeStop: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  customDotHolder: {
    position: 'absolute',
    left: -33,
    backgroundColor: B.white,
    paddingVertical: 2,
  },
  routeLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: B.slate600,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  deleteBtn: { padding: 8 },

  // Photo
  photoSection: { alignItems: 'center', paddingVertical: 40 },
  photoCircleWrapper: { position: 'relative' },
  photoCircle: {
    width: 144,
    height: 144,
    borderRadius: 72,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: B.slate200,
    backgroundColor: B.white,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  photoImage: { width: '100%', height: '100%', borderRadius: 72 },
  cameraBtn: {
    position: 'absolute',
    bottom: 6,
    right: 6,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: B.blue,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: B.bg,
  },

  // Footer
  footer: {
    paddingHorizontal: 24,
    paddingVertical: 24,
    backgroundColor: B.white,
    borderTopWidth: 1,
    borderTopColor: B.slate100,
    alignItems: 'center',
    gap: 4,
  },
  ctaBtn: {
    width: '100%',
    height: 48,
    borderRadius: 22,
    backgroundColor: B.blue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaBtnDisabled: { backgroundColor: B.slate100 },
  ctaBtnSuccess: { backgroundColor: B.emerald500 },
  ctaBtnInner: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  ctaBtnText: { fontSize: 15, fontWeight: '700', color: B.white },
  ctaBtnTextDisabled: { color: B.muted },
  skipBtn: { paddingVertical: 8, paddingHorizontal: 16 },
  skipBtnText: { fontSize: 13, fontWeight: '700', color: B.slate400 },
});
